name: honeywell_reader_android
description: Android implementation of the honeywell_reader_android plugin
repository: https://github.com/merterkoc/honeywell_reader/tree/main/honeywell_reader_android
version: 1.0.0

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.22.0'

flutter:
  plugin:
    implements: honeywell_reader
    platforms:
      android:
        package: com.honeywell.plugins.reader
        pluginClass: HoneywellReaderPlugin
        dartPluginClass: AndroidHoneywellReader

dependencies:
  flutter:
    sdk: flutter
  stream_transform: ^2.1.0
  # honeywell_reader_platform_interface: ^1.0.0
  honeywell_reader_platform_interface:
    path: ../honeywell_reader_platform_interface

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  pigeon: ^22.4.0

topics:
  - honeywell
  - barcode
  - rfid
  - eda52