name: honeywell_rfid_reader_platform_interface
description: "Honeywell RFID Reader Interface"
version: 0.0.3
homepage: https://github.com/merterkoc/honeywell_rfid_reader_package/tree/main/honeywell_rfid_reader_platform_interface

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  plugin_platform_interface: ^2.1.8
  flutter:
    sdk: flutter
#  honeywell_rfid_reader_android:
#    path: ../honeywell_rfid_reader_android

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0