name: honeywell_reader
description: "Honeywell RFID Reader Plugin"
homepage: https://github.com/merterkoc/honeywell_reader_package/tree/main/honeywell_reader
repository: https://github.com/merterkoc/honeywell_reader_package/tree/main/honeywell_reader
version: 0.0.3

environment:
  sdk: ^3.5.0
  flutter: ">=1.20.0"

dependencies:
  permission_handler: ^11.3.1
  flutter:
    sdk: flutter
  honeywell_reader_platform_interface:
    path: ../honeywell_reader_platform_interface
  honeywell_reader_android:
    path: ../honeywell_reader_android

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: honeywell_reader