name: honeywell_rfid_reader
description: "Honeywell RFID Reader Plugin"
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  permission_handler: ^11.3.1
  flutter:
    sdk: flutter
  honeywell_rfid_reader_platform_interface:
    path: ../honeywell_rfid_reader_platform_interface
  honeywell_rfid_reader_android:
    path: ../honeywell_rfid_reader_android

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: honeywell_rfid_reader